apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-app
  namespace: test
spec:
  selector:
    matchLabels:
      app: myapp-app
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp-app
    spec:
      containers:
      - name: gymie
        image: docker.io/utsav0077/pro1:latest # { "$imagepolicy":"test:app" }
        ports:
        - containerPort: 8000
          name: app-port
        env:
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: con-app
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: con-app
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: con-app
              key: PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: con-app
              key: DB-US
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: con-app
              key: DB-US
        # - name: DB_PASSWORD
        #   valueFrom:
        #       secretKeyRef:
        #           name: sec-app
        #           key: DB_PASSWORD
        - name: DB_PASSWORD
          value: secret
