apiVersion:  image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: app
  namespace: test
spec:
  imageRepositoryRef:
    name: app
  filterTags:
    extract: $ts
    pattern: ^main-[a-f0-9]+-(?P<ts>[0-9]+)
  policy:
    numerical:
      order: asc